#!/bin/bash
#SBATCH -J mt_800
#SBATCH -p all
#SBATCH -N 1
#SBATCH -n 1
#SBATCH --mem=20G
#SBATCH -t 0
#SBATCH -o oe/%x-%j.log 
#SBATCH -e oe/%x-%j.err
python single_branch_simulation_random_sample.py -p linear_/ -f 914990 -bn mid -m linear