#!/bin/bash
#SBATCH -J rf_calc
#SBATCH -p all,fat
#SBATCH --exclude node3
#SBATCH -N 1
#SBATCH -n 1
#SBATCH --mem=1G
#SBATCH -t 0
#SBATCH -o oe/%x-%j.log 
#SBATCH -e oe/%x-%j.err
python rf_calc.py -p /data3/wangkun/mtsim_res/20240903/ -i 292066 -m const_100