library(ape)
library(phangorn)
library(getopt)

spec <- matrix(c('filename', 'f', 2, 'character', 'asfd'), byrow=TRUE, ncol=5)
opt <- getopt(spec=spec)
fn <- opt$filename

seq_mt = read.dna(paste('../results/mt_mut_', fn, '.phy',sep=''), format='sequential')
seq_mt_pre = read.dna(paste('../results/mt_mut_pre_', fn, '.phy',sep=''), format='sequential')
seq_mt_dn = read.dna(paste('../results/mt_mut_dn_', fn, '.phy',sep=''), format='sequential')
seq_mt5 = read.dna(paste('../results/mt5_mut_', fn, '.phy',sep=''), format='sequential')
seq_mt5_pre = read.dna(paste('../results/mt5_mut_pre_', fn, '.phy',sep=''), format='sequential')
seq_mt5_dn = read.dna(paste('../results/mt5_mut_dn_', fn, '.phy',sep=''), format='sequential')
seq_mt1 = read.dna(paste('../results/mt1_mut_', fn, '.phy',sep=''), format='sequential')
seq_mt1_pre = read.dna(paste('../results/mt1_mut_pre_', fn, '.phy',sep=''), format='sequential')
seq_mt1_dn = read.dna(paste('../results/mt1_mut_dn_', fn, '.phy',sep=''), format='sequential')
seq_dna = read.dna(paste('../results/dna_mut_', fn, '.phy',sep=''), format='sequential')


dist_mat_mt = dist.dna(seq_mt, model='raw')
dist_mat_mt_pre = dist.dna(seq_mt_pre, model='raw')
dist_mat_mt_dn = dist.dna(seq_mt_dn, model='raw')
dist_mat_mt1 = dist.dna(seq_mt1, model='raw')
dist_mat_mt1_pre = dist.dna(seq_mt1_pre, model='raw')
dist_mat_mt1_dn = dist.dna(seq_mt1_dn, model='raw')
dist_mat_mt5 = dist.dna(seq_mt5, model='raw')
dist_mat_mt5_pre = dist.dna(seq_mt5_pre, model='raw')
dist_mat_mt5_dn = dist.dna(seq_mt5_dn, model='raw')
dist_mat_dna = dist.dna(seq_dna, model='raw')

tree_mt_nj = nj(dist_mat_mt)
tree_mt_pre_nj = nj(dist_mat_mt_pre)
tree_mt_dn_nj = nj(dist_mat_mt_dn)
tree_mt1_nj = nj(dist_mat_mt1)
tree_mt1_pre_nj = nj(dist_mat_mt1_pre)
tree_mt1_dn_nj = nj(dist_mat_mt1_dn)
tree_mt5_nj = nj(dist_mat_mt5)
tree_mt5_pre_nj = nj(dist_mat_mt5_pre)
tree_mt5_dn_nj = nj(dist_mat_mt5_dn)
tree_dna_nj = nj(dist_mat_dna)

seq2_mt <- as.phyDat(seq_mt)
seq2_mt_pre <- as.phyDat(seq_mt_pre)
seq2_mt_dn <- as.phyDat(seq_mt_dn)
seq2_mt1 <- as.phyDat(seq_mt1)
seq2_mt1_pre <- as.phyDat(seq_mt1_pre)
seq2_mt1_dn <- as.phyDat(seq_mt1_dn)
seq2_mt5 <- as.phyDat(seq_mt5)
seq2_mt5_pre <- as.phyDat(seq_mt5_pre)
seq2_mt5_dn <- as.phyDat(seq_mt5_dn)
seq2_dna <- as.phyDat(seq_dna)


tree_mt_mp <- optim.parsimony(tree_mt_nj, seq2_mt)
tree_mt_mp <- nnls.phylo(tree_mt_mp, dist_mat_mt)
tree_mt_pre_mp <- optim.parsimony(tree_mt_pre_nj, seq2_mt_pre)
tree_mt_pre_mp <- nnls.phylo(tree_mt_pre_mp, dist_mat_mt_pre)
tree_mt_dn_mp <- optim.parsimony(tree_mt_dn_nj, seq2_mt_dn)
tree_mt_dn_mp <- nnls.phylo(tree_mt_dn_mp, dist_mat_mt_dn)

tree_mt1_mp <- optim.parsimony(tree_mt1_nj, seq2_mt1)
tree_mt1_mp <- nnls.phylo(tree_mt1_mp, dist_mat_mt1)
tree_mt1_pre_mp <- optim.parsimony(tree_mt1_pre_nj, seq2_mt1_pre)
tree_mt1_pre_mp <- nnls.phylo(tree_mt1_pre_mp, dist_mat_mt1_pre)
tree_mt1_dn_mp <- optim.parsimony(tree_mt1_dn_nj, seq2_mt1_dn)
tree_mt1_dn_mp <- nnls.phylo(tree_mt1_dn_mp, dist_mat_mt1_dn)

tree_mt5_mp <- optim.parsimony(tree_mt5_nj, seq2_mt5)
tree_mt5_mp <- nnls.phylo(tree_mt5_mp, dist_mat_mt5)
tree_mt5_pre_mp <- optim.parsimony(tree_mt5_pre_nj, seq2_mt5_pre)
tree_mt5_pre_mp <- nnls.phylo(tree_mt5_pre_mp, dist_mat_mt5_pre)
tree_mt5_dn_mp <- optim.parsimony(tree_mt5_dn_nj, seq2_mt5_dn)
tree_mt5_dn_mp <- nnls.phylo(tree_mt5_dn_mp, dist_mat_mt5_dn)

tree_dna_mp <- optim.parsimony(tree_dna_nj, seq2_dna)
tree_dna_mp <- nnls.phylo(tree_dna_mp, dist_mat_dna)

write.tree(tree_mt_nj, file=paste('../results/mt_mut_', fn, '_nj.nwk',sep=''))
write.tree(tree_mt_mp, file=paste('../results/mt_mut_', fn, '_mp.nwk',sep=''))
write.tree(tree_mt_pre_mp, file=paste('../results/mt_mut_pre_', fn, '_nj.nwk',sep=''))
write.tree(tree_mt_pre_mp, file=paste('../results/mt_mut_pre_', fn, '_mp.nwk',sep=''))
write.tree(tree_mt_dn_nj, file=paste('../results/mt_mut_dn_', fn, '_nj.nwk',sep=''))
write.tree(tree_mt_dn_mp, file=paste('../results/mt_mut_dn_', fn, '_mp.nwk',sep=''))

write.tree(tree_mt1_nj, file=paste('../results/mt1_mut_', fn, '_nj.nwk',sep=''))
write.tree(tree_mt1_mp, file=paste('../results/mt1_mut_', fn, '_mp.nwk',sep=''))
write.tree(tree_mt1_pre_mp, file=paste('../results/mt1_mut_pre_', fn, '_nj.nwk',sep=''))
write.tree(tree_mt1_pre_mp, file=paste('../results/mt1_mut_pre_', fn, '_mp.nwk',sep=''))
write.tree(tree_mt1_dn_nj, file=paste('../results/mt1_mut_dn_', fn, '_nj.nwk',sep=''))
write.tree(tree_mt1_dn_mp, file=paste('../results/mt1_mut_dn_', fn, '_mp.nwk',sep=''))

write.tree(tree_mt5_nj, file=paste('../results/mt5_mut_', fn, '_nj.nwk',sep=''))
write.tree(tree_mt5_mp, file=paste('../results/mt5_mut_', fn, '_mp.nwk',sep=''))
write.tree(tree_mt5_pre_mp, file=paste('../results/mt5_mut_pre_', fn, '_nj.nwk',sep=''))
write.tree(tree_mt5_pre_mp, file=paste('../results/mt5_mut_pre_', fn, '_mp.nwk',sep=''))
write.tree(tree_mt5_dn_nj, file=paste('../results/mt5_mut_dn_', fn, '_nj.nwk',sep=''))
write.tree(tree_mt5_dn_mp, file=paste('../results/mt5_mut_dn_', fn, '_mp.nwk',sep=''))

write.tree(tree_dna_nj, file=paste('../results/dna_mut_', fn, '_nj.nwk',sep=''))
write.tree(tree_dna_mp, file=paste('../results/dna_mut_', fn, '_mp.nwk',sep=''))
